# Generated by Django 6.0.3 on 2026-03-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('ration_card_no', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('shopkeeper', 'Shopkeeper'), ('user', 'User')], max_length=20)),
            ],
        ),
    ]
