# Generated by Django 6.0.3 on 2026-04-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification_is_active_notification_show_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
